// libs/three/GLTFLoader.js
THREE.GLTFLoader=function(a){THREE.Loader.call(this,a);var b=this,c=new THREE.FileLoader(this.manager);c.setResponseType("arraybuffer");c.setRequestHeader(this.requestHeader);c.setPath(this.path);c.setWithCredentials(this.withCredentials);var d=[],e={};this.register=function(a){return d.push(a),this};this.unregister=function(a){return d.indexOf(a)>-1&&d.splice(d.indexOf(a),1),this};this.setDRACOLoader=function(a){return e[f.KHR_DRACO_MESH_COMPRESSION]=a,this};this.setDDSLoader=
function(a){return e[f.MSFT_TEXTURE_DDS]=a,this};this.setKTX2Loader=function(a){return e[f.KHR_TEXTURE_KTX2]=a,this};this.setMeshoptDecoder=function(a){return e[f.EXT_MESHOPT_COMPRESSION]=a,this};this.parse=function(a,g,h,i){var j,k={json:null,resources:new Map};if(typeof a=="string")j=a;else if(a instanceof ArrayBuffer)if((new DataView(a,0,4)).getUint32(0,true)===n){try{d.forEach(function(a){if(a.name===f.KHR_BINARY_GLTF)throw a})}catch(a){h!==void 0&&h(a);return}var l=
m(a);j=l.content,k.resources=l.resources}else j=(new TextDecoder).decode(a);else j=a;k.json=JSON.parse(j);k.json.asset.version[0]<2&&h!==void 0&&h(new Error("THREE.GLTFLoader: Legacy glTF 1.0 is not supported."));try{this.parseAsync(k,g).then(function(a){h(a)},function(a){i(a)})}catch(a){i(a)}};this.parseAsync=function(a,d){var g=a.json,h=a.resources,i=new o(g,d,e,h);return i.parse().then(function(){return i.gltf})};var f={KHR_BINARY_GLTF:"KHR_binary_glTF",KHR_DRACO_MESH_COMPRESSION:
"KHR_draco_mesh_compression",KHR_LIGHTS_PUNCTUAL:"KHR_lights_punctual",KHR_MATERIALS_CLEARCOAT:"KHR_materials_clearcoat",KHR_MATERIALS_IOR:"KHR_materials_ior",KHR_MATERIALS_PBR_SPECULAR_GLOSSINESS:"KHR_materials_pbrSpecularGlossiness",KHR_MATERIALS_SHEEN:"KHR_materials_sheen",KHR_MATERIALS_SPECULAR:"KHR_materials_specular",KHR_MATERIALS_TRANSMISSION:"KHR_materials_transmission",KHR_MATERIALS_UNLIT:"KHR_materials_unlit",KHR_MATERIALS_VOLUME:"KHR_materials_volume",KHR_TEXTURE_BASISU:
"KHR_texture_basisu",KHR_TEXTURE_KTX2:"KHR_texture_ktx2",KHR_TEXTURE_TRANSFORM:"KHR_texture_transform",KHR_MESH_QUANTIZATION:"KHR_mesh_quantization",EXT_TEXTURE_WEBP:"EXT_texture_webp",EXT_MESHOPT_COMPRESSION:"EXT_meshopt_compression",MSFT_TEXTURE_DDS:"MSFT_texture_dds"},n=1179937895,p={SCALAR:1,VEC2:2,VEC3:3,VEC4:4,MAT2:4,MAT3:9,MAT4:16},q={5120:"BYTE",5121:"UNSIGNED_BYTE",5122:"SHORT",5123:"UNSIGNED_SHORT",5125:"UNSIGNED_INT",5126:"FLOAT"},r={9728:THREE.NearestFilter,
9729:THREE.LinearFilter,9984:THREE.NearestMipmapNearestFilter,9985:THREE.LinearMipmapNearestFilter,9986:THREE.NearestMipmapLinearFilter,9987:THREE.LinearMipmapLinearFilter},s={33071:THREE.ClampToEdgeWrapping,33648:THREE.MirroredRepeatWrapping,10497:THREE.RepeatWrapping},t={ALPHA:"AlphaFormat",RGB:"RGBFormat",RGBA:"RGBAFormat",LUMINANCE:"LuminanceFormat",LUMINANCE_ALPHA:"LuminanceAlphaFormat",RED:"RedFormat"},u={6406:t.ALPHA,6407:t.RGB,6408:t.RGBA,6409:t.LUMINANCE,6410:
t.LUMINANCE_ALPHA,36244:t.RED},v={ALPHA:"1.0",RGB:"1.1",RGBA:"1.1",LUMINANCE:"1.1",LUMINANCE_ALPHA:"1.1",RED:"3.0"},w={FLOAT:Float32Array,UNSIGNED_INT:Uint32Array,UNSIGNED_SHORT:Uint16Array,SHORT:Int16Array,UNSIGNED_BYTE:Uint8Array,BYTE:Int8Array},x={accessor:THREE.InterleavedBuffer,buffer:THREE.BufferAttribute};function m(a){var b=new DataView(a),c=b.getUint32(4,true),d=b.getUint32(8,true);if(c!==n)return console.error("THREE.GLTFLoader: Unsupported glTF-Binary header."),null;var e,
f,g=12;while(g<d){var h=b.getUint32(g,true);g+=4;var i=b.getUint32(g,true);if(g+=4,i===1313821514){var j=new TextDecoder;e=j.decode(new Uint8Array(a,g,h))}else if(i===5130562){var k=g+h;f=a.slice(g,k)}g+=h}var l={content:e,body:f,resources:new Map};return f&&(l.resources.set("$$$",f)),l}function o(a,b,c,d){this.json=a,this.extensions=c,this.options=Object.assign({path:b===""?k(document.baseURI):b,manager:new THREE.LoadingManager,ktx2Loader:null,meshoptDecoder:null,
crossOrigin:"anonymous",fileLoader:new THREE.FileLoader},this.options,d);this.fileLoader=this.options.fileLoader;this.fileLoader.setPath(this.options.path);this.fileLoader.setResponseType("arraybuffer");this.fileLoader.getWithCredentials!==void 0&&this.fileLoader.setWithCredentials(this.options.withCredentials);this.gltf={animations:[],asset:{},cameras:[],materials:[],meshes:[],nodes:[],scenes:[],skins:[],textures:[]};this.cache=new Map;this.primitiveCache=[];this.nodeNamesUsed=
{};this.materialsUsed=[];this.scenesLoaded=!1;this.pending=new Set}var j;if(j=THREE.Cache,j.enabled)this.cache.add("$$$",d.get("$$$"));else{this.cache=d}o.prototype.parse=function(){var a=this,b=this.json;return Promise.all([a.getDependencies("scene"),a.getDependencies("animation"),a.getDependencies("camera")]).then(function(c){var d=a.cache.get("$$$"),e=c[0],f=c[1],g=c[2];return a.buildMaterials(d),a.buildMeshes(d),a.buildSkins(d),a.buildCameras(g),a.buildAnimations(f),
a.buildScenes(e)})};o.prototype.buildMaterials=function(){var a=this,b=this.json,c=b.materials||[];if(c.length===0)return Promise.resolve();var d=c.map(function(c){return a.getDependencies("material",b.materials.indexOf(c))});return Promise.all(d).then(function(d){return Promise.all(d.map(function(d,e){var f=b.materials[e];return a.constructMaterial(f,d)}))})};o.prototype.constructMaterial=function(a,b){var c;if(a.extensions&&a.extensions[f.KHR_MATERIALS_PBR_SPECULAR_GLOSSINESS])c=
new THREE.MeshStandardMaterial;else c=new THREE.MeshPhysicalMaterial;c.name=a.name||"";var d=a.pbrMetallicRoughness||{};c.color=d.baseColorFactor?new THREE.Color().fromArray(d.baseColorFactor):new THREE.Color(16777215);c.metalness=d.metallicFactor!==void 0?d.metallicFactor:1;c.roughness=d.roughnessFactor!==void 0?d.roughnessFactor:.5;b.pbrMetallicRoughness_baseColorTexture&&(c.map=b.pbrMetallicRoughness_baseColorTexture);b.pbrMetallicRoughness_metallicRoughnessTexture&&
(c.metalnessMap=b.pbrMetallicRoughness_metallicRoughnessTexture,c.roughnessMap=b.pbrMetallicRoughness_metallicRoughnessTexture);if(a.extensions){var e=a.extensions[f.KHR_MATERIALS_PBR_SPECULAR_GLOSSINESS];if(e){c.glossiness=e.glossinessFactor!==void 0?e.glossinessFactor:1;c.specular=e.specularFactor?new THREE.Color().fromArray(e.specularFactor):new THREE.Color(16777215);b.KHR_materials_pbrSpecularGlossiness_diffuseTexture&&(c.map=b.KHR_materials_pbrSpecularGlossiness_diffuseTexture,
c.map.encoding=THREE.sRGBEncoding);b.KHR_materials_pbrSpecularGlossiness_specularGlossinessTexture&&(c.specularMap=b.KHR_materials_pbrSpecularGlossiness_specularGlossinessTexture,c.glossinessMap=b.KHR_materials_pbrSpecularGlossiness_specularGlossinessTexture)}}var g=a.normalTexture;g&&(c.normalMap=b.normalTexture,c.normalScale=new THREE.Vector2(1,1),g.scale!==void 0&&(c.normalScale.set(g.scale,g.scale)));var h=a.occlusionTexture;h&&(c.aoMap=b.occlusionTexture,h.strength!==void 0&&
(c.aoMapIntensity=h.strength));var i=a.emissiveTexture;i&&(c.emissiveMap=b.emissiveTexture,c.emissiveMap.encoding=THREE.sRGBEncoding);a.emissiveFactor&&c.emissiveFactor.fromArray(a.emissiveFactor);a.alphaMode&&("BLEND"===a.alphaMode?c.transparent=!0:"MASK"===a.alphaMode&&(c.alphaTest=a.alphaCutoff!==void 0?a.alphaCutoff:.5));a.doubleSided===!0&&(c.side=THREE.DoubleSide);return this.gltf.materials[this.json.materials.indexOf(a)]=c,c};o.prototype.buildMeshes=function(a){var b=
this,c=this.json,d=c.meshes||[],e=c.accessors||[],g=c.bufferViews||[];if(d.length===0)return Promise.resolve();return d.map(function(a){return b.getDependencies("mesh",c.meshes.indexOf(a))})};o.prototype.buildSkins=function(){var a=this,b=this.json,c=b.skins||[];return Promise.all(c.map(function(c,d){return a.getDependencies("skin",d)}))};o.prototype.buildCameras=function(a){for(var b=0,c=this.json.cameras.length;b<c;b++){var d=this.json.cameras[b],e;d.perspective?(e=new THREE.PerspectiveCamera(
THREE.MathUtils.radToDeg(d.perspective.yfov),d.perspective.aspectRatio||1,d.perspective.znear||.01,d.perspective.zfar||2e6),d.perspective.aspectRatio||console.warn("THREE.GLTFLoader: camera.perspective.aspectRatio is not specified; assuming 1.")):d.orthographic&&(e=new THREE.OrthographicCamera(-d.orthographic.xmag,d.orthographic.xmag,d.orthographic.ymag,-d.orthographic.ymag,d.orthographic.znear||.01,d.orthographic.zfar||2e6));d.name&&(e.name=d.name);this.gltf.cameras[b]=e}return Promise.resolve()};
o.prototype.buildAnimations=function(a){var b=this,c=this.json;c.animations=c.animations||[];for(var d=0,e=c.animations.length;d<e;d++){var f=c.animations[d],g=[],h=[],i=[],j=f.name||"animation_"+d;for(var k=0,l=f.channels.length;k<l;k++){var m=f.channels[k],n=f.samplers[m.sampler],o=m.target,p=o.node!==void 0?o.node:o.id,q=c.nodes[p];if(q){var r=o.path,s=r==="weights"?"morphTargetInfluences":r,t=q.name?q.name:q.id;if(s==="translation"||s==="rotation"||s==="scale"){var u=
n.input,v=n.output,w=e[u],x=e[v];if(!w||!x)continue;var y=c.accessors[u],z=c.accessors[v],A=new THREE.KeyframeTrack(t+"."+s,w,x);n.interpolation==="CUBICSPLINE"&&(A.setInterpolation(THREE.InterpolateSmooth),A.createInterpolant=function(a){var b=THREE.KeyframeTrack.prototype.createInterpolant.call(this,a);return b.getSettings=function(){return{endingOffset:this.endingOffset,startTime:this.startTime,endTime:this.endTime}},b}),g.push(A)}else if(s==="weights"){var B=q.mesh,C=c.meshes[
B].primitives[0],D=C.targets.length;if(D>0)for(var E=0;E<D;E++){var F="morphTargetInfluences["+E+"]",G=new THREE.KeyframeTrack(t+"."+F,e[n.input],e[n.output]);g.push(G)}}}}if(g.length>0)var H=new THREE.AnimationClip(j,void 0,g);this.gltf.animations[d]=H}return Promise.resolve()};o.prototype.buildScenes=function(a){var b=this,c=this.json.scenes,d=this.gltf;return Promise.all(c.map(function(e,f){var g=new THREE.Scene;e.name&&(g.name=e.name);e.nodes.forEach(function(h){g.add(
d.nodes[h])});b.scenesLoaded||(d.scene=g,b.scenesLoaded=!0);return d.scenes[f]=g,Promise.resolve()}))};o.prototype.getDependencies=function(a,b){switch(a){case"scene":return this._getSceneDependencies(b);case"animation":return this._getAnimationDependencies(b);case"camera":return this._getCameraDependencies(b);case"material":return this._getMaterialDependencies(b);case"mesh":return this._getMeshDependencies(b);case"skin":return this._getSkinDependencies(b);default:return Promise.resolve([])}};
o.prototype._getSceneDependencies=function(a){var b=this,c=this.json.scenes[a],d=c.nodes||[],e=d.map(function(a){return b._getNodeDependencies(a)});return Promise.all(e).then(function(a){return a.reduce(function(a,b){return a.concat(b)},[])})};o.prototype._getNodeDependencies=function(a){var b=this,c=this.json.nodes[a],d=[];c.mesh!==void 0&&(d=d.concat(b._getMeshDependencies(c.mesh)));c.camera!==void 0&&(d=d.concat(b._getCameraDependencies(c.camera)));c.skin!==void 0&&
(d=d.concat(b._getSkinDependencies(c.skin)));var e=c.children||[],f=e.map(function(a){return b._getNodeDependencies(a)});return Promise.all(f).then(function(a){return d.concat(a.reduce(function(a,b){return a.concat(b)},[]))})};o.prototype._getCameraDependencies=function(a){return Promise.resolve([])};o.prototype._getAnimationDependencies=function(a){var b=this.json.animations[a],c=[],d=b.channels||[],e=b.samplers||[];for(var f=0,g=d.length;f<g;f++){var h=d[f],i=
h.sampler,j=e[i];c.push(this._getAccessorDependencies(j.input)),c.push(this._getAccessorDependencies(j.output))}return Promise.all(c)};o.prototype._getMaterialDependencies=function(a){var b=this,c=this.json.materials[a],d=[];if(c.pbrMetallicRoughness){var e=c.pbrMetallicRoughness;e.baseColorTexture&&d.push(b._getTextureDependencies(e.baseColorTexture.index)),e.metallicRoughnessTexture&&d.push(b._getTextureDependencies(e.metallicRoughnessTexture.index))}c.normalTexture&&
d.push(b._getTextureDependencies(c.normalTexture.index));c.occlusionTexture&&d.push(b._getTextureDependencies(c.occlusionTexture.index));c.emissiveTexture&&d.push(b._getTextureDependencies(c.emissiveTexture.index));var g=c.extensions&&c.extensions[f.KHR_MATERIALS_PBR_SPECULAR_GLOSSINESS];return g&&(g.diffuseTexture&&d.push(b._getTextureDependencies(g.diffuseTexture.index)),g.specularGlossinessTexture&&d.push(b._getTextureDependencies(g.specularGlossinessTexture.index))),
Promise.all(d)};o.prototype._getMeshDependencies=function(a){var b=this,c=this.json.meshes[a],d=c.primitives.map(function(a){var c=[];return a.indices!==void 0&&c.push(b._getAccessorDependencies(a.indices)),a.material!==void 0&&c.push(b._getMaterialDependencies(a.material)),Object.keys(a.attributes).forEach(function(d){c.push(b._getAccessorDependencies(a.attributes[d]))}),a.targets&&a.targets.forEach(function(a){Object.keys(a).forEach(function(d){c.push(b._getAccessorDependencies(
a[d]))})}),Promise.all(c).then(function(a){return a.reduce(function(a,b){return a.concat(b)},[])})});return Promise.all(d).then(function(a){return a.reduce(function(a,b){return a.concat(b)},[])})};o.prototype._getSkinDependencies=function(a){var b=this,c=this.json.skins[a],d=[];return c.inverseBindMatrices!==void 0&&d.push(b._getAccessorDependencies(c.inverseBindMatrices)),Promise.all(d)};o.prototype._getTextureDependencies=function(a){var b=this.json.textures[a],
c=b.source;return this._getImageDependencies(c)};o.prototype._getImageDependencies=function(a){var b=this.json.images[a],c=b.uri,d=b.bufferView,e=[];if(c)e.push(this._getURIDependencies(c));else if(d!==void 0)e.push(this._getBufferViewDependencies(d));return Promise.all(e)};o.prototype._getAccessorDependencies=function(a){var b=this.json.accessors[a],c=[];return b.bufferView!==void 0?c.push(this._getBufferViewDependencies(b.bufferView)):b.sparse!==void 0&&(c.push(this._getBufferViewDependencies(
b.sparse.indices.bufferView)),c.push(this._getBufferViewDependencies(b.sparse.values.bufferView))),Promise.all(c)};o.prototype._getBufferViewDependencies=function(a){var b=this.json.bufferViews[a],c=[];return c.push(this._getBufferDependencies(b.buffer)),Promise.all(c)};o.prototype._getBufferDependencies=function(a){var b=this.json.buffers[a];return b.uri?this._getURIDependencies(b.uri):Promise.resolve([])};o.prototype._getURIDependencies=function(a){var c=this,
d=this.options.manager,e=this.cache,g=this.fileLoader;return new Promise(function(h,i){if(e.has(a))return h(e.get(a));d.itemStart(a);g.load(a,function(b){e.add(a,b),d.itemEnd(a),h(b)},void 0,function(b){i(b),d.itemError(a),d.itemEnd(a)})})}function k(a){var b=a.split("/");return b.pop(),b.join("/")+"/"}}