// libs/three/OrbitControls.js
THREE.OrbitControls=function(a,b){this.object=a;this.domElement=b!==void 0?b:document;this.enabled=!0;this.target=new THREE.Vector3;this.minDistance=0;this.maxDistance=Infinity;this.minZoom=0;this.maxZoom=Infinity;this.minPolarAngle=0;this.maxPolarAngle=Math.PI;this.minAzimuthAngle=-Infinity;this.maxAzimuthAngle=Infinity;this.enableDamping=!1;this.dampingFactor=.25;this.enableZoom=!0;this.zoomSpeed=1;this.enableRotate=!0;this.rotateSpeed=1;this.enablePan=!0;this.panSpeed=1;this.screenSpacePanning=!1;
this.keyPanSpeed=7;this.autoRotate=!1;this.autoRotateSpeed=2;this.keys={LEFT:37,UP:38,RIGHT:39,BOTTOM:40};this.mouseButtons={LEFT:THREE.MOUSE.ROTATE,MIDDLE:THREE.MOUSE.DOLLY,RIGHT:THREE.MOUSE.PAN};this.touches={ONE:THREE.TOUCH.ROTATE,TWO:THREE.TOUCH.DOLLY_PAN};var c=this;this.target0=this.target.clone();this.position0=this.object.position.clone();this.zoom0=this.object.zoom;var d=new THREE.Vector3,e=1,f=new THREE.Vector2,g=new THREE.Vector2,h=new THREE.Vector2,i=new THREE.Vector2,
j=new THREE.Vector2,k=new THREE.Vector2,l=new THREE.Vector2,m=new THREE.Vector2,n=new THREE.Vector2,o=[],p=0,q=new THREE.Vector3,r=!1,s=0,t=1,u=2,v=3;this.getPolarAngle=function(){return d.getPolarAngle()};this.getAzimuthalAngle=function(){return d.getAzimuthalAngle()};this.saveState=function(){c.target0.copy(c.target);c.position0.copy(c.object.position);c.zoom0=c.object.zoom};this.reset=function(){c.target.copy(c.target0);c.object.position.copy(c.position0);c.object.zoom=
c.zoom0;c.object.updateProjectionMatrix();c.dispatchEvent(v);c.update();s=t};this.update=function(){var a=new THREE.Vector3,b=new THREE.Quaternion().setFromUnitVectors(c.object.up,new THREE.Vector3(0,1,0)),e=b.clone().inverse(),f=new THREE.Vector2,g=new THREE.Vector2;return function(){var h=c.object.position;a.copy(h).sub(c.target);a.applyQuaternion(b);d.setFromVector3(a);c.autoRotate&&s===t&&O(P());d.theta<c.minAzimuthAngle?(d.theta=c.minAzimuthAngle,c.dispatchEvent(v)):d.theta>
c.maxAzimuthAngle&&(d.theta=c.maxAzimuthAngle,c.dispatchEvent(v));d.phi=Math.max(c.minPolarAngle,Math.min(c.maxPolarAngle,d.phi));d.makeSafe();d.radius*=e;d.radius=Math.max(c.minDistance,Math.min(c.maxDistance,d.radius));c.target.add(q);a.setFromSpherical(d);a.applyQuaternion(e);h.copy(c.target).add(a);c.object.lookAt(c.target);c.enableDamping===!0?q.multiplyScalar(1-c.dampingFactor):q.set(0,0,0);var i=!1;return f.distanceToSquared(g)>Number.EPSILON&&(c.dispatchEvent(v),f.copy(g),
i=!0),i}}();this.dispose=function(){c.domElement.removeEventListener("contextmenu",I,!1);c.domElement.removeEventListener("pointerdown",x,!1);c.domElement.removeEventListener("wheel",K,!1);c.domElement.removeEventListener("touchstart",L,!1);c.domElement.removeEventListener("touchend",N,!1);c.domElement.removeEventListener("touchmove",M,!1);document.removeEventListener("pointermove",z,!1);document.removeEventListener("pointerup",A,!1);window.removeEventListener("keydown",J,!1)};var w=
Object.assign(Object.create(THREE.EventDispatcher.prototype),{constructor:this});for(var x in w)this[x]=w[x];c.domElement.addEventListener("contextmenu",I,!1);c.domElement.addEventListener("pointerdown",y,!1);c.domElement.addEventListener("wheel",K,{passive:!1});c.domElement.addEventListener("touchstart",L,{passive:!1});c.domElement.addEventListener("touchend",N,!1);c.domElement.addEventListener("touchmove",M,{passive:!1});window.addEventListener("keydown",J,!1);function y(a){s!==t&&
c.domElement.setPointerCapture(a.pointerId),document.addEventListener("pointermove",z,!1),document.addEventListener("pointerup",A,!1),B(a)}function z(a){r||(c.domElement.hasPointerCapture(a.pointerId)===!1||C(a))}function A(a){o.length===0&&(c.domElement.releasePointerCapture(a.pointerId),document.removeEventListener("pointermove",z,!1),document.removeEventListener("pointerup",A,!1)),s=t,r=!1}function B(a){if(o.length===0)s=u;else{var b=D(a);o[b]&&(s=u,o.splice(b,1))}var d=F(a.pointerId);d.pointer=
a;d.event=new PointerEvent(a.type,a);d.down.set(a.clientX,a.clientY);o.push(d)}function C(a){for(var b=0;b<o.length;b++)if(o[b].pointer.pointerId===a.pointerId){o[b].pointer=a,o[b].event=new PointerEvent(a.type,a);return}s=u}function D(a){for(var b=0;b<o.length;b++)if(o[b].pointer.pointerId===a.pointerId)return b}function E(a){for(var b=0;b<o.length;b++)if(o[b].pointer.pointerId===a.pointerId){o.splice(b,1);return}}function F(a){for(var b=0;b<p;b++)if(o[b].id===a)return o[b];var c=new THREE.Vector2,
d=new THREE.Vector2,e=new THREE.Vector2;return{id:a,pointer:null,event:null,down:c,current:d,previous:e}}function G(){return c.domElement.clientWidth}function H(){return c.domElement.clientHeight}function I(a){c.enablePan&&a.preventDefault()}function J(a){c.enabled!==!1&&c.enablePan&&(r=!0,q.set(0,0,0),a.keyCode===c.keys.UP?q.y=1:a.keyCode===c.keys.BOTTOM?q.y=-1:a.keyCode===c.keys.LEFT?q.x=1:a.keyCode===c.keys.RIGHT&&(q.x=-1),q.multiplyScalar(c.keyPanSpeed/c.domElement.clientHeight),
c.update())}function K(a){c.enabled!==!1&&c.enableZoom&&(a.preventDefault(),a.stopPropagation(),s=t,a.deltaY<0?e/=Math.pow(.95,c.zoomSpeed):a.deltaY>0&&(e*=Math.pow(.95,c.zoomSpeed)),c.update())}function L(a){c.enabled!==!1&&(a.preventDefault(),s=u,o.length===1?(f.set(a.touches[0].pageX,a.touches[0].pageY),g.copy(f)):o.length===2&&(h.set(a.touches[0].pageX,a.touches[0].pageY),i.set(a.touches[1].pageX,a.touches[1].pageY),j.copy(h).add(i).multiplyScalar(.5),k.set(h.x-i.x,h.y-i.y)))}
function M(a){if(c.enabled!==!1){a.preventDefault(),a.stopPropagation(),s=u;var b=o.length;if(b===1){g.set(a.touches[0].pageX,a.touches[0].pageY);var d=f.clone().sub(g);f.copy(g);var e=2*Math.PI*d.x/G()*c.rotateSpeed,h=2*Math.PI*d.y/H()*c.rotateSpeed;d.theta-=e,d.phi-=h,c.update()}else if(b===2){l.set(a.touches[0].pageX,a.touches[0].pageY),m.set(a.touches[1].pageX,a.touches[1].pageY);var i=j.clone().sub(l.clone().add(m).multiplyScalar(.5));j.copy(l).add(m).multiplyScalar(.5);
var n=k.clone().sub(l.clone().sub(m));k.copy(l).sub(m),e=Math.pow(n.length()/k.length(),c.zoomSpeed),d.radius/=e,c.screenSpacePanning===!0?Q(i):R(i),c.update()}}}function N(a){c.enabled!==!1&&(s=t)}function O(a){d.theta-=a}function P(){return 2*Math.PI*c.autoRotateSpeed/60}function Q(a){var b=a.x/G(),d=a.y/H();q.x-=b,q.y+=d,c.update()}function R(a){var b=2*d.radius*a.x/G(),e=2*d.radius*a.y/H();q.x-=b,q.y+=e,c.update()}}